# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '*/3 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.TOKEN }}
        stale-issue-message: 'This issue is being closed due to inactivity.'
        stale-pr-message: 'This PR is being closed due to inactivity.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        stale-issue-days: 0  # Directly marks issues as stale without delay
        stale-pr-days: 0     # Directly marks PRs as stale without delay
        close-issues: true   # Automatically close issues after they are marked stale
        close-pull-requests: true  # Automatically close PRs after they are marked stale
